# Этот файл отключает автоматический деплой
name: Disable Auto Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  disable:
    runs-on: ubuntu-latest
    steps:
    - name: Disable auto deploy
      run: echo "Auto deploy disabled"
